//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Engine;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="FeeServiceSoap", Namespace="http://sms.360buy.com/")]
public partial class FeeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetBalanceOperationCompleted;
    
    private System.Threading.SendOrPostCallback KouBalanceOperationCompleted;
    
    /// <remarks/>
    public FeeService() {
        this.Url =  ConfigXml.GetXmlNode("KoufeiUrl", "");
        //this.Url = "http://127.0.0.1/jd/feeservice.asmx";
    }
    
    /// <remarks/>
    public event GetBalanceCompletedEventHandler GetBalanceCompleted;
    
    /// <remarks/>
    public event KouBalanceCompletedEventHandler KouBalanceCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.360buy.com/GetBalance", RequestNamespace="http://sms.360buy.com/", ResponseNamespace="http://sms.360buy.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int GetBalance(string loginname, string ctime, string mypwd) {
        object[] results = this.Invoke("GetBalance", new object[] {
                    loginname,
                    ctime,
                    mypwd});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetBalance(string loginname, string ctime, string mypwd, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBalance", new object[] {
                    loginname,
                    ctime,
                    mypwd}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndGetBalance(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void GetBalanceAsync(string loginname, string ctime, string mypwd) {
        this.GetBalanceAsync(loginname, ctime, mypwd, null);
    }
    
    /// <remarks/>
    public void GetBalanceAsync(string loginname, string ctime, string mypwd, object userState) {
        if ((this.GetBalanceOperationCompleted == null)) {
            this.GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceOperationCompleted);
        }
        this.InvokeAsync("GetBalance", new object[] {
                    loginname,
                    ctime,
                    mypwd}, this.GetBalanceOperationCompleted, userState);
    }
    
    private void OnGetBalanceOperationCompleted(object arg) {
        if ((this.GetBalanceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sms.360buy.com/KouBalance", RequestNamespace="http://sms.360buy.com/", ResponseNamespace="http://sms.360buy.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int KouBalance(string loginname, string ctime, int fee, string mypwd) {
        object[] results = this.Invoke("KouBalance", new object[] {
                    loginname,
                    ctime,
                    fee,
                    mypwd});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginKouBalance(string loginname, string ctime, int fee, string mypwd, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("KouBalance", new object[] {
                    loginname,
                    ctime,
                    fee,
                    mypwd}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndKouBalance(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void KouBalanceAsync(string loginname, string ctime, int fee, string mypwd) {
        this.KouBalanceAsync(loginname, ctime, fee, mypwd, null);
    }
    
    /// <remarks/>
    public void KouBalanceAsync(string loginname, string ctime, int fee, string mypwd, object userState) {
        if ((this.KouBalanceOperationCompleted == null)) {
            this.KouBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKouBalanceOperationCompleted);
        }
        this.InvokeAsync("KouBalance", new object[] {
                    loginname,
                    ctime,
                    fee,
                    mypwd}, this.KouBalanceOperationCompleted, userState);
    }
    
    private void OnKouBalanceOperationCompleted(object arg) {
        if ((this.KouBalanceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.KouBalanceCompleted(this, new KouBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void GetBalanceCompletedEventHandler(object sender, GetBalanceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void KouBalanceCompletedEventHandler(object sender, KouBalanceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class KouBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal KouBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
